name: verilog-ci
on: [push, pull_request]
jobs:
  lint-and-sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator iverilog
      - name: Check no for/generate
        run: 10_sim/check_forbidden.sh
      - name: Lint (Verilator)
        run: make lint
      - name: Simulate (Icarus)
        run: make SIM=icarus run
